version: "3"

vars:
  DOCKER_IMAGE: buckee-control-plane
  DOCKER_TAG: latest

tasks:
  default:
    cmd: task -a

  clean:
    cmd: go clean

  build:bin:
    deps:
      - clean
    cmd: go build -o main .

  package:docker:
    prompt: You are about to build a Docker image tagged as '{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}'. Are you sure you want to proceed?
    cmd: docker build -t {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} .

  local:host:run:
    cmd: go run .

  local:host:ping:
    vars:
      PORT: 8080
    cmd: curl 127.0.0.1:{{.PORT}}/ping

  local:kind:load-docker-image:
    preconditions:
      - kind get clusters | grep 'kind'
    deps:
      - package:docker
    prompt: You are about to load the Docker image '{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}' into the Kind cluster. Are you sure you want to proceed?"
    cmd: kind load docker-image {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}
