version: "3"

vars:
  CONTROL_PLANE_DIR: src/control-plane

includes:
  control-plane:
    taskfile: "{{.CONTROL_PLANE_DIR}}/Taskfile.yaml"
    dir: "{{.CONTROL_PLANE_DIR}}"

tasks:
  default:
    cmd: task -a
