version: "3"

vars:
  CORE_DIR: src/core
  INFRA_DIR: src/infra

includes:
  core:
    taskfile: "{{.CORE_DIR}}/Taskfile.yaml"
    dir: "{{.CORE_DIR}}"
  infra:
    taskfile: "{{.INFRA_DIR}}/Taskfile.yaml"
    dir: "{{.INFRA_DIR}}"

tasks:
  default:
    cmd: task -a
