version: "3"

vars:
  CORE_DIR: src/core

includes:
  core:
    taskfile: "{{.CORE_DIR}}/Taskfile.yaml"
    dir: "{{.CORE_DIR}}"

tasks:
  default:
    cmd: task -a

  local:kind:create-cluster:
    status:
      - kind get clusters | grep "kind"
    cmd: kind create cluster

  local:kind:delete-cluster:
    preconditions:
      - kind get clusters | grep "kind"
    cmd: kind delete cluster

  local:kind:images:
    preconditions:
      - kind get clusters | grep "kind"
    vars:
      NODE_NAME: kind-control-plane
    cmd: docker exec -it {{.NODE_NAME}} crictl images
