version: "3"

vars:
  CONTROL_PLANE_DIR: src/control-plane
  INFRA_DIR: src/infra

includes:
  core:
    taskfile: "{{.CONTROL_PLANE_DIR}}/Taskfile.yaml"
    dir: "{{.CONTROL_PLANE_DIR}}"
  infra:
    taskfile: "{{.INFRA_DIR}}/Taskfile.yaml"
    dir: "{{.INFRA_DIR}}"

tasks:
  default:
    cmd: task -a
