apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default.yaml
secretGenerator:
  - namespace: crossplane-system
    name: aws-credentials
    files:
      - credentials=private-credentials
generatorOptions:
  disableNameSuffixHash: true
