apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-default.yaml
secretGenerator:
  - name: aws-credentials
    namespace: crossplane-system
    files:
      - credentials=private-credentials
generatorOptions:
  disableNameSuffixHash: true
