apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: buckee
spec:
  forProvider:
    region: us-east-1
    vpcConfig:
      - subnetIdRefs:
          - name: buckee-us-east-1a
          - name: buckee-us-east-1b
    roleArnRef:
      name: eks-cluster
  providerConfigRef:
    name: default
