apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: buckee
  labels:
    vpc-name: buckee
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 172.16.0.0/16
  providerConfigRef:
    name: default
