apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: eks-cluster
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    managedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
