apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: buckee-us-east-1a
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 172.16.0.0/20
    vpcIdSelector:
      matchLabels:
        vpc-name: buckee
  providerConfigRef:
    name: aws-default
