apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: buckee
spec:
  forProvider:
    imageTagMutability: IMMUTABLE
    region: us-east-1
  providerConfigRef:
    name: aws-default
