version: "3"

vars:
  PROVIDERS_DIR: providers
  PROVIDER_CONFIGS_DIR: provider-configs
  ROLES_DIR: roles
  VPCS_DIR: vpcs
  SUBNETS_DIR: subnets
  REPOSITORIES_DIR: repositories

  CROSSPLANE_REPOSITORY_NAME: crossplane-stable
  CROSSPLANE_REPOSITORY_URL: https://charts.crossplane.io/stable
  CROSSPLANE_NAMESPACE: crossplane-system

tasks:
  default:
    cmd: task -a

  local:kind:create-cluster:
    status:
      - kind get clusters | grep 'kind'
    cmd: kind create cluster

  local:kind:delete-cluster:
    preconditions:
      - kind get clusters | grep 'kind'
    prompt: You are about to delete the Kind cluster. This action cannot be undone. Are you sure you want to proceed?
    cmd: kind delete cluster

  local:kind:images:
    preconditions:
      - kind get clusters | grep 'kind'
    vars:
      NODE_NAME: kind-control-plane
    cmd: docker exec -it {{.NODE_NAME}} crictl images

  local:kind:crds:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get crds

  local:kind:crossplane:add-repository:
    preconditions:
      - kind get clusters | grep 'kind'
    status:
      - helm repo list | grep {{.CROSSPLANE_REPOSITORY_NAME}}
    cmd: helm repo add {{.CROSSPLANE_REPOSITORY_NAME}} {{.CROSSPLANE_REPOSITORY_URL}}

  local:kind:crossplane:install:
    preconditions:
      - kind get clusters | grep 'kind'
    status:
      - kubectl get pods -n {{.CROSSPLANE_NAMESPACE}} | grep 'crossplane'
    deps:
      - local:kind:crossplane:add-repository
    prompt: You are about to install Crossplane in the Kind cluster under the namespace '{{.CROSSPLANE_NAMESPACE}}'. Are you sure you want to proceed?
    vars:
      CHART_NAME: crossplane
    cmd: helm install {{.CHART_NAME}} {{.CROSSPLANE_REPOSITORY_NAME}}/{{.CHART_NAME}} -n {{.CROSSPLANE_NAMESPACE}} --create-namespace --wait

  local:kind:crossplane:providers:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get providers

  local:kind:crossplane:providers:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.PROVIDERS_DIR}}

  local:kind:crossplane:providers:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.PROVIDERS_DIR}}

  local:kind:crossplane:provider-configs:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get providerconfigs

  local:kind:crossplane:provider-configs:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.PROVIDER_CONFIGS_DIR}}

  local:kind:crossplane:provider-configs:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.PROVIDER_CONFIGS_DIR}}

  aws:kind:crossplane:roles:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get roles

  aws:kind:crossplane:roles:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.ROLES_DIR}}

  aws:kind:crossplane:roles:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.ROLES_DIR}}

  aws:kind:crossplane:vpcs:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get vpcs

  aws:kind:crossplane:vpcs:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.VPCS_DIR}}

  aws:kind:crossplane:vpcs:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.VPCS_DIR}}

  aws:kind:crossplane:subnets:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get subnets

  aws:kind:crossplane:subnets:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.SUBNETS_DIR}}

  aws:kind:crossplane:subnets:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.SUBNETS_DIR}}

  aws:kind:crossplane:repositories:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl get repositories

  aws:kind:crossplane:repositories:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl apply -k {{.REPOSITORIES_DIR}}

  aws:kind:crossplane:repositories:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmd: kubectl delete -k {{.REPOSITORIES_DIR}}

  aws:kind:crossplane:apply:
    preconditions:
      - kind get clusters | grep 'kind'
    cmds:
      - task: aws:kind:crossplane:roles:apply
      - task: aws:kind:crossplane:vpcs:apply
      - task: aws:kind:crossplane:subnets:apply
      - task: aws:kind:crossplane:repositories:apply

  aws:kind:crossplane:delete:
    preconditions:
      - kind get clusters | grep 'kind'
    cmds:
      - task: aws:kind:crossplane:repositories:delete
      - task: aws:kind:crossplane:subnets:delete
      - task: aws:kind:crossplane:vpcs:delete
      - task: aws:kind:crossplane:roles:apply

  aws:ecr:authenticate-docker-client:
    cmd: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin {{.AWS_ECR_REGISTRY}}
